# Generated by Django 2.1.2 on 2018-11-23 03:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='newuser',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newuser',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newuser',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
