# Generated by Django 2.1.2 on 2018-11-30 06:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181129_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerartisans',
            name='artisan_skill',
            field=models.CharField(choices=[('A/C Maintenace', 'air-conditions'), ('Plumbing', 'plumbing'), ('Hygeine-Cleaning', 'hygiene-cleaning'), ('Car-Wash', 'car wash'), ('Electrical-Wiring', 'electrical-wiring'), ('Electrical-Electronics', 'electrical-electronics'), ('Engineering-Auto', 'engineering-auto'), ('Engineering-Generators', 'engineering-generators'), ('Driving-Trucks', 'driving-trucks'), ('Driving-HeavyDuty', 'driving-Heavy-Duty'), ('Driving-Automobile', 'driving-automobile'), ('Medicals-Nurse', 'medicals-nurse')], default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerartisans',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
