# Generated by Django 2.1.2 on 2018-11-30 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181130_0621'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisterArtisans',
            new_name='RegisterArtisan',
        ),
    ]
